Repository hrdyjan1/Fitme, pull requests merged in 2020-11, with the labels that each got.

#2 Initialized Eslint/Prettier
  frontend/.eslintrc.json
  frontend/.prettierrc
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/App.test.jsx
  frontend/src/Routes.jsx
  frontend/src/index.jsx
  frontend/src/pages/HomePage.jsx
  frontend/src/pages/LoginPage.js
  frontend/src/pages/PageNotFound.jsx
  frontend/src/utils/apollo.jsx
  frontend/src/utils/auth.jsx
  frontend/yarn.lock
  yarn.lock
Labels: good first issue

#8 Renamed jsx to js
  frontend/.eslintrc.json
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/Routes.js
  frontend/src/index.js
  frontend/src/pages/HomePage.js
  frontend/src/pages/PageNotFound.js
  frontend/src/utils/apollo.js
  frontend/src/utils/auth.js
Labels: bug

#9 Hotfix/fm 5 renamed auth
  backend/src/index.js
Labels: bug

#10 FM-6 Initialized user and places methods
  backend/src/constants/checkIfValidEmail.js
  backend/src/constants/regex.js
  backend/src/constants/uuid.js
  backend/src/index.js
  backend/src/modules/place/index.js
  backend/src/modules/place/mutation.js
  backend/src/modules/rootResolver.js
  backend/src/modules/user/mutation.js
Labels: sprint1

#11 FM- Added mail logic
  backend/package.json
  backend/src/index.js
  backend/src/modules/user/mutation.js
  backend/yarn.lock
Labels: sprint1

#19 User signin,signup (persistance)
  frontend/src/App.js
  frontend/src/Routes.js
  frontend/src/components/SignUpDialog.js
  frontend/src/constants/functions.js
  frontend/src/constants/object.js
  frontend/src/constants/regex.js
  frontend/src/contexts/user.js
  frontend/src/contexts/user/helpers.js
  frontend/src/contexts/user/index.js
  frontend/src/pages/HomePage.js
  frontend/src/pages/PageNotFound.js
  frontend/src/pages/SignInPage.js
  frontend/src/utils/auth.js
  frontend/src/utils/auth/context.js
  frontend/src/utils/auth/index.js
  frontend/src/utils/auth/usePersistedAuth.js
  frontend/src/utils/storage.js
Labels: sprint2

#22 Feature/fm 8 signin dialog
  frontend/package.json
  frontend/src/constants/functions.js
  frontend/src/contexts/user/helpers.js
  frontend/src/contexts/user/index.js
  frontend/src/organisms/SignInDialog.js
  frontend/src/organisms/SignUpDialog.js
  frontend/src/organisms/header/Buttons.js
  frontend/src/organisms/index.js
  frontend/src/pages/HomePage.js
  frontend/src/pages/PageNotFound.js
  frontend/src/pages/SignInPage.js
  frontend/src/pages/Verification.js
  frontend/src/utils/storage.js
  frontend/yarn.lock
  yarn.lock
Labels: sprint2

#24 Feature/fm 6 send real email
  backend/src/modules/user/mutation.js
Labels: sprint2

#26 Feature/fm 7 forgot password
  backend/src/index.js
  backend/src/modules/user/mutation.js
  backend/src/utils/email.js
  frontend/src/constants/functions.js
  frontend/src/pages/PageNotFound.js
  frontend/src/pages/ResetPassword.js
  frontend/src/pages/Verification.js
Labels: sprint2

#28 Feature/fm 9 top bar user menu
  frontend/src/Routes.js
  frontend/src/atoms/header/userNameButton.js
  frontend/src/molecules/header/UserButtons.js
  frontend/src/molecules/header/UserMenu.js
  frontend/src/organisms/SignInDialog.js
  frontend/src/organisms/SignUpDialog.js
  frontend/src/organisms/header/Buttons.js
  frontend/src/pages/HomePage.js
  frontend/src/pages/UserProfilePage.js
  frontend/src/pages/index.js
Labels: enhancement, sprint2

#32 Feature/fm 8 enable change pass
  frontend/src/Routes.js
  frontend/src/atoms/header/userNameButton.js
  frontend/src/constants/functions.js
  frontend/src/constants/routes.js
  frontend/src/molecules/header/UserButtons.js
  frontend/src/molecules/header/UserMenu.js
  frontend/src/organisms/forgotPass/helpers.js
  frontend/src/organisms/forgotPass/index.js
  frontend/src/organisms/header/Buttons.js
  frontend/src/organisms/index.js
  frontend/src/pages/HomePage.js
  frontend/src/pages/ResetPassword.js
  frontend/src/pages/UserProfilePage.js
  frontend/src/pages/index.js
  frontend/src/utils/apollo.js
Labels: sprint2

#33 added password hashing with argon2 function
  backend/src/modules/user/mutation.js
Labels: sprint2

#36 FM-14 Enabled FE and BE change profile photo
  backend/package.json
  backend/src/index.js
  backend/src/modules/user/mutation.js
  backend/src/utils/cloudinary.js
  backend/yarn.lock
  frontend/package.json
  frontend/src/Routes.js
  frontend/src/constants/routes.js
  frontend/src/pages/UploadImagePage.js
  frontend/src/pages/index.js
  frontend/src/utils/apollo.js
  frontend/yarn.lock
Labels: sprint2

#43 FM-15 Moved forgot pass to sigin
  frontend/src/molecules/header/UserButtons.js
  frontend/src/organisms/SignInDialog.js
  frontend/src/organisms/header/TopBar.js
  frontend/src/pages/HomePage.js
Labels: sprint2

#44 Hotfix/double header
  frontend/src/pages/ResetPassword.js
  frontend/src/pages/Verification.js
Labels: sprint2

#50 Feature/fm 16 sport places
  frontend/assets/images/runner.jpg
  frontend/package.json
  frontend/public/basket.jpg
  frontend/public/index.html
  frontend/public/runner.jpg
  frontend/public/sport.png
  frontend/public/sport2.png
  frontend/src/App.js
  frontend/src/Routes.js
  frontend/src/components/atoms/FormikPasswordField.js
  frontend/src/components/atoms/FormikTextField.js
  frontend/src/components/atoms/header/UserNameButton.js
  frontend/src/components/atoms/image/index.js
  frontend/src/components/atoms/index.js
  frontend/src/components/molecules/ProfilePicture.js
  frontend/src/components/molecules/header/UserButtons.js
  frontend/src/components/molecules/header/UserMenu.js
  frontend/src/components/molecules/index.js
  frontend/src/components/molecules/sectionHeader/index.js
  frontend/src/components/organisms/AddressForm.js
  frontend/src/components/organisms/CardForm.js
  frontend/src/components/organisms/ChangePasswordForm.js
  frontend/src/components/organisms/ContactInfoForm.js
  frontend/src/components/organisms/ImageForm.js
  frontend/src/components/organisms/Section.js
  frontend/src/components/organisms/SignInDialog.js
  frontend/src/components/organisms/SignUpDialog.js
  frontend/src/components/organisms/forgotPass/helpers.js
  frontend/src/components/organisms/forgotPass/index.js
  frontend/src/components/organisms/header/Buttons.js
  frontend/src/components/organisms/header/TopBar.js
  frontend/src/components/organisms/header/navbar/components/Button.js
  frontend/src/components/organisms/header/navbar/components/Buttons.js
  frontend/src/components/organisms/header/navbar/components/style.css
  frontend/src/components/organisms/header/navbar/helpers.js
  frontend/src/components/organisms/header/navbar/index.js
  frontend/src/components/organisms/header/navbar/style.css
  frontend/src/components/organisms/index.js
  frontend/src/components/spec/Footer.js
  frontend/src/components/spec/Hero.js
  frontend/src/components/spec/Overview.js
  frontend/src/components/spec/SportPlaces.js
  frontend/src/constants/palette.js
  frontend/src/constants/routes.js
  frontend/src/constants/theme.js
  frontend/src/index.css
  frontend/src/pages/HomePage.js
  frontend/src/pages/ResetPassword.js
  frontend/src/pages/UserProfilePage.js
  frontend/src/templates/UserProfileTemplate.js
  frontend/yarn.lock
Labels: sprint3

#51 FM-16 Fixed alert message
  frontend/package.json
  frontend/src/App.js
  frontend/src/Routes.js
  frontend/src/components/organisms/SignInDialog.js
  frontend/src/components/organisms/SignUpDialog.js
  frontend/src/components/organisms/forgotPass/helpers.js
  frontend/src/components/organisms/forgotPass/index.js
  frontend/src/components/organisms/header/navbar/index.js
  frontend/src/components/spec/Footer.js
  frontend/src/components/spec/Overview.js
  frontend/src/components/spec/SportPlaces.js
  frontend/src/components/spec/hero/Hero.js
  frontend/src/components/spec/hero/helpers.js
  frontend/src/constants/functions/basic.js
  frontend/src/constants/functions/createCtx.js
  frontend/src/constants/routes.js
  frontend/src/constants/validTexts.js
  frontend/src/contexts/notification.js
  frontend/src/contexts/user/helpers.js
  frontend/src/contexts/user/index.js
  frontend/src/pages/HomePage.js
  frontend/src/pages/ResetPassword.js
  frontend/src/pages/SignInPage.js
  frontend/src/pages/UploadImagePage.js
  frontend/src/pages/UserProfilePage.js
  frontend/src/pages/Verification.js
  frontend/src/utils/auth/context.js
  frontend/yarn.lock
Labels: sprint3

#52 Feature/fm 17 logout
  frontend/src/Routes.js
  frontend/src/components/organisms/SignInDialog.js
  frontend/src/components/organisms/header/navbar/helpers.js
  frontend/src/components/organisms/header/navbar/index.js
  frontend/src/components/organisms/index.js
  frontend/src/components/organisms/logout/index.js
  frontend/src/components/spec/Overview.js
  frontend/src/components/spec/SportPlaces.js
  frontend/src/components/spec/hero/Hero.js
  frontend/src/constants/routes.js
  frontend/src/contexts/notification.js
  frontend/src/pages/ResetPassword.js
  frontend/src/pages/SignInPage.js
  frontend/src/pages/SportPlacesPage.js
  frontend/src/pages/UploadImagePage.js
  frontend/src/pages/Verification.js
  frontend/src/pages/index.js
Labels: sprint3

#55 Feature/fm 18 sport place edit
  frontend/public/sport3.png
  frontend/public/sport4.jpg
  frontend/src/Routes.js
  frontend/src/components/organisms/account/components/Gallery/Gallery.js
  frontend/src/components/organisms/account/components/Gallery/index.js
  frontend/src/components/organisms/account/components/General/General.js
  frontend/src/components/organisms/account/components/General/index.js
  frontend/src/components/organisms/account/components/Hero/Hero.js
  frontend/src/components/organisms/account/components/Hero/index.js
  frontend/src/components/organisms/account/components/Security/Security.js
  frontend/src/components/organisms/account/components/Security/index.js
  frontend/src/components/organisms/account/components/Tags/Tags.js
  frontend/src/components/organisms/account/components/Tags/index.js
  frontend/src/components/organisms/account/components/Trainers/Trainers.js
  frontend/src/components/organisms/account/components/Trainers/index.js
  frontend/src/components/organisms/account/components/index.js
  frontend/src/components/organisms/account/index.js
  frontend/src/components/organisms/cardBase/index.js
  frontend/src/components/organisms/header/navbar/helpers.js
  frontend/src/components/organisms/sectionAlternate/index.js
  frontend/src/components/spec/Overview.js
  frontend/src/components/spec/SportPlaces.js
  frontend/src/components/spec/hero/Hero.js
  frontend/src/components/spec/hero/helpers.js
  frontend/src/constants/routes.js
Labels: sprint3
